spring:
  application:
    name: moddo
  config:
    import: classpath:config/application-jwt.yml, classpath:config/application-s3.yml
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 30
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
    show-sql: true

server:
  address: 0.0.0.0
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

cookie:
  http-only: false
  path: /
  same-site: none
  max-age: 7D

---

spring:
  config:
    import: classpath:config/application-dev.yml
    activate:
      on-profile: dev

---

spring:
  config:
    import: classpath:config/application-prod.yml
    activate:
      on-profile: prod

---





